name: data_collection
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  connectivity_plus: ^6.1.0
  provider: ^6.1.2
  path: ^1.9.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  http: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # Add the assets section to include your logo
  assets:
    - assets/images/logo1.png
    - assets/icons/home.png
    - assets/icons/assessments.png
    - assets/icons/uploads.png
    - assets/icons/profile.png

  # You can include additional assets or fonts here as needed.
